### ISSUE TITLE
Detect newer available version

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#109]
It could be suggested in wrapper generator. There are two cases:
* we generate wrappers for versions e.g. v2.0.1, v2.1 (creates wrapper `V2`), and there's a new version v2.2 - then it needs bumping the version in the existing wrapper request
* we generate wrappers for major versions e.g. v2, v3, and there's a new version v4 - then suggest adding a new wrapper request

**Comment by krzema12** [comment]
Maybe this GitHub API could be used:
* https://docs.github.com/en/rest/reference/git#list-matching-references
* https://api.github.com/repos/actions/checkout/git/matching-refs/tags/v

**Comment by krzema12** [comment]
@jmfayard quick workaround: we could do it less often than wrapper regeneration, like once a week, and then it would have to be a separate workflow. It would then allow us to add like 1-2-minute waiting between the requests so that we don't cross the rate limit.

**Comment by jmfayard** [comment]
Actually it's fine, the rate limit is high enough once we are logged in with a `GITHUB_TOKEN`

`x-ratelimit-limit: 60` is for an authentificated call

**Comment by krzema12** [comment]
@jmfayard did you mean **un**authenticated? :)

**Comment by jmfayard** [comment]
Correct :)
