### ISSUE TITLE
Expose test report in GitHub

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#116]
Sometimes the console output doesn't show details about a failed unit test, it just says it failed. We need more details, e. g. the difference in asserted string. It's especially convenient for Windows runner where it's not trivial to use Windows for Linux users.

**Comment by jmfayard** [comment]
@krzema12 the best & easiest way to do that in my experience is to enable the Gradle Build Scan
as I did there https://github.com/krzema12/github-actions-kotlin-dsl/blob/20580c018023311c0acf2d9945033d428d398fac/settings.gradle.kts#L1-L12

See my failing build https://github.com/krzema12/github-actions-kotlin-dsl/actions/runs/1945775537

**Comment by krzema12** [comment]
Thanks, looks promising. Is it free forever? [Here](https://gradle.com/pricing/) I'm reading about 30-day trial, [here](https://gradle.com/enterprise-customers/oss-projects/) I see that only chosen open-source projects are supported?

**Comment by jmfayard** [comment]
@krzema12 The part where it publishes a build scan under a public URL is free for ever.
There are other parts of Gradle Enterprise (like running tests in parallel, ....) that are not free, but none of our concern here.

**Comment by krzema12** [comment]
Cool, let's go forward with it then :) I'll add it in spare moment, or feel free to submit a PR.
