### ISSUE TITLE
Publish nightly builds

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#135]
Each commit to main branch (or in fact any branch, for easier development) could publish the library to some repo, not Maven Central.

**Comment by NikkyAI** [comment]
to make this work with jitpack do this:

1. add `jitpack.yml` to the repo

`jitpack.yml`

```
install:
  - echo "Running a custom install command"
  - ./gradlew clean :library:publishToMavenLocal -xtest -xsignMavenJavaPublication
```

see https://github.com/NikkyAI/github-actions-kotlin-dsl/blob/main/jitpack.yml

2. use this in your script

```kotlin
@file:Repository("https://jitpack.io")
@file:DependsOn("com.github.krzema12:github-actions-kotlin-dsl:main-SNAPSHOT")
```

make sure that the `jitpack.yml` file exists on whatever branch/commit you request from jitpack, without it will fail to build the artifacts

**Comment by krzema12** [comment]
Left: mention using nightly builds in the docs.

**Comment by krzema12** [comment]
Thanks @NikkyAI for the great idea with JitPack!
