### ISSUE TITLE
[Bug] Getting Started page isn't rendered correctly

### ISSUE THREAD

**Issue by polarene** [krzema12/github-actions-kotlin-dsl#153]
# Action
 
The [Getting Started](https://krzema12.github.io/github-actions-kotlin-dsl/user-guide/getting_started/) page isn't rendered correctly.

# Expected

The list should be rendered correctly as in the markdown preview: https://github.com/krzema12/github-actions-kotlin-dsl/blob/main/docs/user-guide/getting_started.md

# Actual

Points 4,5 of the numbered list are rendered as part of a paragraph from point 3.

<img width="752" alt="Schermata 2022-03-23 alle 08 28 26" src="https://user-images.githubusercontent.com/858624/159647475-4ed685a7-ab54-45b8-b778-1ccf8780df2d.png">

Maybe it could be a bug in the version of _mkdocs_ used.

**Comment by polarene** [comment]
I found out that correcting some indentation and line breaks, it renders correctly
https://github.com/krzema12/github-actions-kotlin-dsl/pull/154

**Comment by krzema12** [comment]
Thanks, good catch!

**Comment by polarene** [comment]
Thank you for the adjustments, now it renders perfectly.
