### ISSUE TITLE
Versioning for script-generator

### ISSUE THREAD

**Issue by jmfayard** [krzema12/github-actions-kotlin-dsl#167]
Currently, `script-generator`:

- depends directly on the `library` and `wrapper-generator` module i.e. whatever is on the main branch
- produces a script that depends on the latest published version, for example `@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.12.0")`

That was the only viable option while I was working on it, but now this is suboptimal because:

- it may use features that are not published yet, so the script doesn't compile
- if there is a breaking change, you can't publish `library` until you have updated `script-generator`

It would be better to depend instead on `implementation("it.krzeminski:github-actions-kotlin-dsl:0.12.0")`

I think that this requires the `wrapper-generator` to be published too

-- Edit

`wrapper-generator` can be fetched from jitpack as well
see https://github.com/jitpack/gradle-modular

**Comment by krzema12** [comment]
Quick idea: consume what's needed through JitPack. This way the clients could choose a version of the lib they use and use the corresponding script generator. I'd like to avoid publishing anything apart from the library itself to Maven Central. JitPack seems like a good, lightweight alternative.

**Comment by krzema12** [comment]
@jmfayard I found a simpler solution: #168

**Comment by krzema12** [comment]
Use https://pypi.org/project/mkdocs-markdownextradata-plugin/ to keep version in the docs in one place. See the comment in #168

**Comment by krzema12** [comment]
Done in https://github.com/krzema12/github-actions-kotlin-dsl/commit/0d1110084e0dc6df5adbc6565b38b3d186120f95
