### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#18]
* [ ] how to use
* [ ] how to contribute, especially add new actions
* [ ] deploy automatically on tags publishing? together with the lib

**Comment by krzema12** [comment]
What's popular: https://github.com/facebook/docusaurus

**Comment by jmfayard** [comment]
I can totally recommend https://squidfunk.github.io/mkdocs-material/ that I use in https://jmfayard.github.io/refreshVersions/

It's simply a list of markdown files in the `docs` folder
Plus this file `mkdocs.yml` https://github.com/jmfayard/refreshVersions/blob/main/mkdocs.yml

**Comment by krzema12** [comment]
Initial table of contents:

* Introduction _(rationale, benefits)_
* Getting started _(quick, simple example)_
* User guide
  * Entering the Kotlin DSL world _(show YAML and Kotlin DSL, explain similarities and differences, general approach how to think about this library in terms of its API)_
  * Using actions _(wrappers existing in the library, defining custom ones, adding new wrappers to the library)_
  * Dealing with multiple workflows _(e.g. single script to write all YAMLs)_
  * Consuming action outputs _(accessing placeholders)_
* Contributing _(guidelines, rules)_
* Projects using this library
* Frequently Asked Questions

**Comment by krzema12** [comment]
What was done: moved stuff from README to separately hosted docs. Anything more should be added either together with adding/changing something in the library itself, or as a result of user feedback.
