### ISSUE TITLE
Propose collaboration with GitHub

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#227]
https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback
If GitHub provided some API that would allow to hide the YAML, it would simplify a lot.

**Comment by krzema12** [comment]
Draft below

----

# Problem statement

Currently the only way of defining a workflow is using YAML. It has its drawbacks (add link here) and while it works fine with simple workflows, it becomes unmaintainable with the more complex ones.

That's why I came up with an idea to use a general-purpose language to describe the workflows. I'm the creator and co-maintainer of GitHub Actions Kotlin DSL. It works by having Kotlin scripts using the DSL to generate the YAML, and during job runtime the script and the YAML are compared to ensure they are in sync.

It does fix several issues that one can experience with YAML, but it's not comfortable to integrate with GitHub.... 

# Proposed solution

* executable files with ".workflow." in name are treated as workflow generators
* workflow generator is ran either at the beginning of workflow run, or secretly by GitHub during saving the file in the repo
* the user doesn't see the YAML as a separate file, at most they can see it in the workflow output for debugging purposes

**Comment by jmfayard** [comment]
Some suggestions:

## gitignore

We can simply git ignore the workflow files. This way we can debug what's going on with the YAML if it fails.

```
# .gitignore
.github/workflows/*.yml
.github/workflows/*.yaml
```

## init.sh script

GitHub could recognize that a shell script `.github/workflows/init.sh` is present

For users of the Kotlin DSL, it would contain

```sh
#!/usr/bin/env sh
./build.main.kts
./update-gradle-wrapper.main.kts
echo "YAML wrappers updated"
```

The good thing with a shell script is that it's technology agnostic.

If someone wants to produce its workflow in JavaScript, that would be 

```sh
#!/usr/bin/env sh
node generate-wrappers.js
echo "YAML wrappers updated"
```

**Comment by krzema12** [comment]
Thanks @jmfayard!

> We can simply git ignore the workflow files. This way we can debug what's going on with the YAML if it fails.

How would it look like step by step? I thought about showing the YAML only in workflow log for debugging purposes, not having actual YAML files in the repo. There's also one edge case: someone may want to have both YAML and scripts, then ignoring YAMLs with glob pattern would be undesired.

> GitHub could recognize that a shell script `.github/workflows/init.sh` is present

What advantage does it bring over the mechanism I presented? Mine is platform-agnostic as well, and you don't have to maintain an extra file (`init.sh`) which adds extra work for the user. Also there's a question what would be the API of this script. Would it write YAML to files as we do now in the library?

**Comment by jmfayard** [comment]
`init.sh` would be the equivalent of our current `_GenerateWorkflows.main.kts`
Yes it would write YAML to files.
How it does it is up to the script author and whatever technology it uses.

About git-ignoring the YAML files that would be of course optional.

My use case is that I want to push only the changes to the Kotlin scripts and not have a scenario where my YAML files sare not up to date. Usually that should be enough. But the workflow may still fail on the CI and I want to investigate why. So I run the script locally and can inspect the (.gitignored) YAML files.

**Comment by krzema12** [comment]
Looks like both approaches has its pros and cons, plus our preferences play some role. Whatever would be implemented by GitHub highly depends on their current internal implementation of actions. Primarily, when and how often they need to access the YAML, e. g. to read the triggers.

I'll write what you propose as an alternative, and will state that these are just examples of possible APIs that need to be checked against how things work now. These will get us stated with the discussion.

**Comment by krzema12** [comment]
Posted here: https://github.com/github/feedback/discussions/15904
I'd appreciate showing some support in this thread :)

**Comment by krzema12** [comment]
Nothing more to do here, apart from bumping the thread (which may look a bit rude) and waiting until the library has better adoption.
