### ISSUE TITLE
[Bug] NoClassDefFoundError: MalformedYamlException

### ISSUE THREAD

**Issue by jmfayard** [krzema12/github-actions-kotlin-dsl#228]
# Action

Trying to run any workflow with `@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.15.0")`

# Expected

I take any hello world workflow who compiles and run with `@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.13.0")`

I upgrade to 0.15.0 and expects it to work

# Actual

```
java.lang.NoClassDefFoundError: com/charleskorn/kaml/MalformedYamlException
        at it.krzeminski.githubactions.yaml.ToYamlKt.generateYaml(ToYaml.kt:98)
        at it.krzeminski.githubactions.yaml.ToYamlKt.writeToFile(ToYaml.kt:21)
        at Integration_main.<init>(integration.main.kts:48)
Caused by: java.lang.ClassNotFoundException: com.charleskorn.kaml.MalformedYamlException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

# Workaround, if exists

I didn't find one.

I trtied to find where kotlin puts its cache and dependencies cache on macOS but to no avail

**Comment by krzema12** [comment]
I already migrated this repo's workflows to 0.15.0 and they work fine. I think there's something specifically wrong with your workflow. Could you give an example `.main.kts` file where the problem reproduces?

**Comment by jmfayard** [comment]
Problem solved, I had a version of Kotlin 1.3 and JVM 8

Maybe worth adding to the website:

```bash
$ open https://sdkman.io/
$ sdk install java 17.0.3-oracle
$ sdk install kotlin 1.6.21

$ kotlin -version
Kotlin version 1.6.21-release-334 (JRE 17.0.3+8-LTS-111)

$ java -version
java version "17.0.3" 2022-04-19 LTS
Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)
```

**Comment by krzema12** [comment]
Thanks, I'll try to add a runtime check, and first figure out what are the minimal versions.

**Comment by krzema12** [comment]
I decided to just improve the docs, it's challenging to add runtime validation which may be fragile anyway.
