### ISSUE TITLE
Provide first-party API to output files directly

### ISSUE THREAD

**Issue by msfjarvis** [krzema12/github-actions-kotlin-dsl#23]
Rather than encouraging users to pipe files it'd be easier to to have something like a `Workflow.writeToFile(inputPath: Path, outputPath: Path)` API. This also allows users like me with a lot of [workflows](https://github.com/android-password-store/Android-Password-Store/tree/develop/.github/workflows) to be able to generate all of the outputs in one go without having to resort to too much shell scripting. Having at least the output path be a property in the workflow would also help simplify this. Ultimately I envision being able to do something like this in a CI workflow to automatically update YAML files without requiring a consistency check job in each individual workflow

```
#!/usr/bin/env kscript
 
@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.2.0")

//INCLUDE workflow1.kt
//INCLUDE workflow2.kt
//INCLUDE workflow3.kt
//INCLUDE workflow4.kt

arrayOf(workflow1, workflow2, workflow3, workflow4).forEach { workflow ->
  workflow.writeToFile() // implicitly uses an output parameter provided in the workflow itself
}

```

**Comment by krzema12** [comment]
Thanks for the feedback!

Actually you can do it without piping or shell scripting already, sort of. The current `toYaml` function returns a YAML as a string, it's a matter of writing it to a file. If I get you correctly, you'd like workflow objects to be self-contained, so that you can just call `writeToFile` without passing the paths separately, right?

**Comment by msfjarvis** [comment]
> Thanks for the feedback!
> 
> Actually you can do it without piping or shell scripting already, sort of. The current `toYaml` function returns a YAML as a string, it's a matter of writing it to a file. If I get you correctly, you'd like workflow objects to be self-contained, so that you can just call `writeToFile` without passing the paths separately, right?

That's right. I want to add a CI job that is run when any of the GHA Kotlin DSL files are changed which would update the YAML, and avoid the overhead of checking the workflow file for consistency on every run of the workflow.

**Comment by krzema12** [comment]
Code complete. I'll release next version within a day or two.

**Comment by msfjarvis** [comment]
New API looks great, thanks for fixing this so quickly! Excited to try this out once released 👍🏼
