### ISSUE TITLE
No possibility to override built-in keys

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-actions-kotlin-dsl#292]
To work-around #288 I tried different things to get an own `uses` value.
One of the things I tried was
```kts
_customArguments = mapOf(
    "uses" to StringCustomValue("./")
)
```
which resulted in a duplicate key error.

It would be nice if keys from `_customArguments`  could override built-in keys for working-around cases not covered by the DSL yet.

**Comment by krzema12** [comment]
Yep, totally agree.

**Comment by krzema12** [comment]
See https://github.com/krzema12/github-actions-kotlin-dsl/issues/80#issuecomment-1200504222, it will be fixed in scope of that task.

**Comment by krzema12** [comment]
After addressing #80, it now works properly. See e.g. this test for jobs:

https://github.com/krzema12/github-actions-kotlin-dsl/blob/9f803d557aa073c9dc35f6ecdc70807726cfe55f/library/src/test/kotlin/it/krzeminski/githubactions/yaml/JobsToYamlTest.kt#L273-L308
