### ISSUE TITLE
[Core feature request] Document `expr(...)`

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-actions-kotlin-dsl#295]
`expr(...)` can be quite useful to write more readable code, it should be documented. :-)

**Comment by jmfayard** [comment]
`expr(...)` on steroids is coming in this PR :)
https://github.com/krzema12/github-actions-kotlin-dsl/pull/204

**Comment by jmfayard** [comment]
Doc is now here
https://github.com/krzema12/github-actions-kotlin-dsl/pull/331
 https://github.com/krzema12/github-actions-kotlin-dsl/blob/docs-typesafe-expressions/docs/user-guide/typesafe-expressions.md

**Comment by krzema12** [comment]
Docs deployed as https://krzema12.github.io/github-actions-kotlin-dsl/user-guide/type-safe-expressions/, resolving.
