### ISSUE TITLE
[Feature] add flag to disable the generation of check_yaml_consistency

### ISSUE THREAD

**Issue by uweschaefer** [krzema12/github-actions-kotlin-dsl#316]
# Action

It'd be nice to be able to skip the mentioned job as it takes 30s to execute on every commit. We could have release-prepare scripts that make sure that the yaml is fresh by executing the kts files.

# Expected

Something like `workflow(disableConsistencyCheck = false,...`
so that users could opt-out if needed.

# Actual

There is no way around the generation of the job, as far as i can see?

**Comment by uweschaefer** [comment]
Sorry, this is not really a bug, but the current project-gh-templates do not allow to create an issue without it.

**Comment by krzema12** [comment]
It's already there :)

https://github.com/krzema12/github-actions-kotlin-dsl/blob/1394a0d479e6d078ae1b5cc9c7fdadb3ddb10da0/library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt#L18
