### ISSUE TITLE
[Action wrapper(s) request] sonarcloud-github-action

### ISSUE THREAD

**Issue by uweschaefer** [krzema12/github-actions-kotlin-dsl#410]
### Are you sure the action(s) you want aren't already supported?

Yes

### What action(s) do you need?
https://github.com/SonarSource/sonarcloud-github-action

**Comment by krzema12** [comment]
Thanks, it should be released this Friday.

**Comment by uweschaefer** [comment]
no need to rush. Thanks Piotr.
