### ISSUE TITLE
Periodic jobs are ran for forked repos

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#441]
It's usually not needed, and needlessly consumes shared resources. The jobs are usually needed only for the original repo since they help keeping the action wrappers up-to-date.

**Comment by krzema12** [comment]
Original, schedule: yes
Original, not schedule: yes
Fork, schedule: **no**
Fork, not schedule: yes

Run if original or not schedule.

**Comment by krzema12** [comment]
TODO: ask fork owners to update the forks.

**Comment by krzema12** [comment]
@Goooler the fix is merged, could you please sync [your fork](https://github.com/Goooler/github-actions-kotlin-dsl) and check if these workflows aren't run on schedule?

**Comment by Goooler** [comment]
Synced.

**Comment by krzema12** [comment]
Next step: check tomorrow here https://github.com/Goooler/github-actions-kotlin-dsl/actions?query=event%3a schedule if the jobs are still ran.

**Comment by krzema12** [comment]
@aSemy
@cybernetics
@ema987
@jmfayard
@LeoColman
@LouisCAD
@madhead
@NikkyAI
@polarene
@scottbisaillon
@uweschaefer
@Vampire

Please sync your forks with the newest commit on parent's `main` branch. The goal is to save GitHub resources by not running periodic jobs in the forks.
Once you do so, please give me a :+1: under this comment. Thanks!

**Comment by jmfayard** [comment]
Thanks for that, it was a bit annoying!

**Comment by cybernetics** [comment]
synced

**Comment by Vampire** [comment]
I don't have workflows enabled, they are disabled by default for forks.

**Comment by polarene** [comment]
I just deleted the fork, I don't remember why I made it in the first place. Thanks for pointing this out.
