### ISSUE TITLE
Generate action wrappers code

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#71]
There should be a piece of logic that, given basic info about the action, generates Kotlin code.

**Comment by jmfayard** [comment]
I can work on that if you want @krzema12 
I have experience working with https://github.com/square/kotlinpoet

**Comment by krzema12** [comment]
That would be really cool, let's try that! I thought about kotlinpoet, but then I figured it will be simpler to generate the whole code by hand because I don't have experience with kotlinpoet. However, I'm open to checking how kotlinpoet will work for us.

So far I don't have much: https://github.com/krzema12/github-actions-kotlin-dsl/commits/generator .
Quickly describing my idea and plan:
* an independent Gradle module that handles wrappers code generation. Input for a single wrapper: actions's owner, name and version. Output: wrapper's code and target path
* have a central place with a list of wrappers that should be generated
* each wrapper should be customizable in terms of e.g. how a certain input should be modeled. Default is a string, but one could use various modes like "integer with special value" or "enumeration with custom value"
* generating the wrappers on demand, not during building the library. In the future, we can thought about making it more intelligent, e.g. (re)generating only these that need to be (re)generated
* best if generated code was kept in another source set, to distinguish it from the manually written code
* prior to generation, remove all generated code so that no leftover from previous generations is left
* have solid tests for different edge cases

**Comment by jmfayard** [comment]
Nice!
