### ISSUE TITLE
[Core feature request] Overriding Action versions and additional Yaml properties

### ISSUE THREAD

**Issue by jmfayard** [krzema12/github-actions-kotlin-dsl#74]
**What feature do you need?**

More possibility for the developer to override an Action's version, add additional properties, check that the version is valid.

Currently the release of GitHub actions and of the github-actions-kotlin-dsl library are too tightly coupled.

**Do you have an example usage?**

Given an action  like this one:

```
data class CreateBranchV2(
    val branch: String? = null,
    val sha: String? = null,
) : Action("peterjgrainger", "action-create-branch", "v2.0.0") {
}
```

I would like to be able to specify a specific version

```
val action = CreateBranchV2(branch = "main").withVersion("v2.1.0")
```

It may be the case the this release added two new parameters `fast` and `nice` who is not yet supported and I don't want to wait for a release of github-actions-kotlin-dsl.

I would then like to be able to specify an untyped map of additional Yaml Properties

```
val action = CreateBranchV2(branch = "main")
    .withVersion("v2.1.0")
    .withAdditionalYaml("fast" to "true", "nice" to "yes please")
```

An issue with this is that it's easy to specify a wrong version and waste too much time on the CI.

It would be nice if the `.withVersion("v2.1.0")` does check that the release actually exists

That can be done with either a request like this:

`curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/peterjgrainger/action-create-branch/releases`

or

`curl --location --head 'https://github.com/peterjgrainger/action-create-branch/releases/tag/v2.1.0'`

It would be nice to cache the result that a given release exists, so that we pay the network penalty only once.

**Comment by krzema12** [comment]
Let's remember about updating the docs. I think a whole chapter on using custom attributes/inputs should be created, something that will answer "some feature is not yet in the library - what can I do as a workaround?".
